### ISSUE TITLE
Error with v0.4.1 docker 

### ISSUE THREAD

**Issue by GLCNI** [NethermindEth/juno#962]
**Juno Docker Version:** v0.4.1
**OS:** Ubuntu 20.04LTS
Using docker-compose 

I get “hardware” related error using version v0.4.1 when starting the docker container. 
```
[+] Running 3/3
 ✔ Network starknet-node_default                                                                                                                                Created        0.2s
 ✔ Container starknet-node-starknet-node-1                                                                                                                      Started        0.9s
 ! starknet-node The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested                0.0s
```

Log output 
```
starknet-node-starknet-node-1  | exec /usr/local/bin/juno: exec format error
starknet-node-starknet-node-1  | exec /usr/local/bin/juno: exec format error
starknet-node-starknet-node-1  | exec /usr/local/bin/juno: exec format error
```

VPS used, CPU details:
Architecture:                    x86_64
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           60
Model name:                      Intel Core Processor (Haswell, no TSX)

**Other attempts:**
If this was an issue with hardware, I tried to run this locally 

Local hardware, CPU details:
Architecture:                    x86_64
CPU
CPU family:                      25
Model:                           80
Model name:                      AMD Ryzen 7 5700G with Radeon Graphics

Same error
![image](https://github.com/NethermindEth/juno/assets/67609618/cd09e6f4-0817-4d18-887c-4c8456eb88a6)

**Solution:** 
In both deployments, local and VPS, rolling back to version v0.4.0 worked, there was nothing wrong with the configuration it seems to be with the docker image.

**Comment by GLCNI** [comment]
thanks, that must be the problem then image tag I was using was `nethermindeth/juno:v0.4.1`

this is the template:
```
version: '3.3'
services:
    starknet-node:
        image: 'nethermindeth/juno:v0.4.0'
        user: 1000:1000
        restart: always
        stop_grace_period: 30s
        volumes:
            - /home/$USER/starknet-node/data:/var/lib/juno
        ports:
            - '0.0.0.0:6060:6060'
            - '0.0.0.0:6061:6061'
        command:
            --db-path '/var/lib/juno'
            --eth-node '<ETH-NODE-ADDRESS>'
            --log-level 'info'
            --network 'mainnet'
            --http-port '6060' 
            --ws-port '6061'
        logging:
          driver: json-file
          options:
            max-size: 10m
            max-file: "10"

```

will correct to `nethermind/juno:v0.4.1`
